# Preprocess all the matches

#### Libraries

In [25]:
import pandas as pd
import os
from pathlib import Path
from tqdm import tqdm
from datetime import datetime

#### Functions

In [26]:
def load_all_df(folder_path) -> pd.DataFrame:
    folder = Path(folder_path)

    df = pd.DataFrame()
    
    for subdir, dirs, files in os.walk(folder):
        for file in tqdm(sorted(files), total=len(files)-1):
            if file.endswith('.csv'):
                file_path = os.path.join(subdir, file)
                data = pd.read_csv(file_path)
                df = pd.concat([df, data], axis = 0)

    return df

In [27]:
def clean_df(data):

    tourney_id = data['tourney_id']\
        .astype(str)\
        .rename('tourney_id')
    
    tour_year = data['tourney_id']\
        .astype(str)\
        .str[:4]\
        .rename('tour_year')
    
    tourney_name = data['tourney_name']\
        .astype(str)\
        .rename('tourney_name')
    
    surface = data['surface']\
        .astype(str)\
        .fillna('Unknown')\
        .replace('nan', 'Unknown')\
        .rename('surface')
    
    # draw_size = data['draw_size']\
    #     .fillna(0)\
    #     .replace('nan', 0)\
    #     .astype(int)\
    #     .rename('draw_size')
    
    tourney_level = data["tourney_level"]\
        .astype(str)\
        .rename('tourney_level')
    
    tourney_date = pd.to_datetime(data['tourney_date'], format='%Y%m%d').rename('tourney_date')
    
    match_num = data["match_num"]\
        .astype(int)\
        .rename('match_num')
    
    match_id = (data['tourney_id'].astype(str) + data['match_num'].astype(str))\
        .astype(str)\
        .rename('match_id')

    score = data["score"]\
        .astype(str)\
        .replace('nan', 'Unknown')\
        .rename('score')
    
    best_of = data["best_of"]\
        .astype(int)\
        .rename('best_of')
    
    round = data["round"]\
        .astype(str)\
        .rename('round')

    num_sets = data['score']\
        .apply(lambda x: len(x.split()) if isinstance(x, str) else 0)\
        .rename('num_sets')
    

    winner_id = data['winner_id']\
        .astype(int)\
        .rename('winner_id')
    
    winner_name = data['winner_name']\
        .astype(str)\
        .rename('winner_name')
    
    # winner_rank_points = data['winner_rank_points']\
    #     .astype(int)\
    #     .rename('winner_rank_points')
    
    loser_id = data['loser_id']\
        .astype(int)\
        .rename('loser_id')
    
    loser_name = data['loser_name']\
        .astype(str)\
        .rename('loser_name')
    
    # loser_rank_points = data['loser_rank_points']\
    #     .astype(int)\
    #     .rename('loser_rank_points')
    
    cleaned_df = pd.concat(
        [   
            match_id,
            tour_year,
            tourney_id, 
            tourney_name, 
            surface, 
            # draw_size, 
            tourney_level, 
            tourney_date, 
            match_num, 
            score, 
            best_of, 
            round, 
            num_sets,
            winner_id, 
            winner_name, 
            # winner_rank_points, 
            loser_id, 
            loser_name],
            # loser_rank_points], 
         axis=1)
    
    assert cleaned_df.isna().sum().sum() == 0,\
        f'There are {cleaned_df.isna().sum()} nan values'
    
    return cleaned_df.sort_values('tourney_date').reset_index(drop=True)

#### Treating data

In [28]:
dataframe = load_all_df('../data/atp_matches')
wta_dataframe = load_all_df('../data/wta_matches')

55it [00:05,  9.21it/s]
57it [00:04, 13.12it/s]

In [30]:
clean_data = clean_df(dataframe)
clean_wta_data = clean_df(wta_dataframe)

In [31]:
clean_data.columns

Index(['match_id', 'tour_year', 'tourney_id', 'tourney_name', 'surface',
       'tourney_level', 'tourney_date', 'match_num', 'score', 'best_of',
       'round', 'num_sets', 'winner_id', 'winner_name', 'loser_id',
       'loser_name'],
      dtype='object')

In [32]:
clean_wta_data.columns

Index(['match_id', 'tour_year', 'tourney_id', 'tourney_name', 'surface',
       'tourney_level', 'tourney_date', 'match_num', 'score', 'best_of',
       'round', 'num_sets', 'winner_id', 'winner_name', 'loser_id',
       'loser_name'],
      dtype='object')

In [33]:
clean_data.isna().sum()

match_id         0
tour_year        0
tourney_id       0
tourney_name     0
surface          0
tourney_level    0
tourney_date     0
match_num        0
score            0
best_of          0
round            0
num_sets         0
winner_id        0
winner_name      0
loser_id         0
loser_name       0
dtype: int64

In [34]:
clean_wta_data.isna().sum()

match_id         0
tour_year        0
tourney_id       0
tourney_name     0
surface          0
tourney_level    0
tourney_date     0
match_num        0
score            0
best_of          0
round            0
num_sets         0
winner_id        0
winner_name      0
loser_id         0
loser_name       0
dtype: int64

#### Save data to csv

In [35]:
clean_data.to_csv('../web_data/clean_atp_matches.csv')
clean_wta_data.to_csv('../web_data/clean_wta_matches.csv')

# Players

In [36]:
players = pd.read_csv('../data/atp_players.csv')
wta_players = pd.read_csv('../data/wta_players.csv')

/var/folders/s3/s4gmfm1j23xg8_5fnbsqlflm0000gp/T/ipykernel_61765/1323896356.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('../data/atp_players.csv')
/var/folders/s3/s4gmfm1j23xg8_5fnbsqlflm0000gp/T/ipykernel_61765/1323896356.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  wta_players = pd.read_csv('../data/wta_players.csv')

In [37]:
wta_players.isna().sum()

player_id          0
name_first      4208
name_last          0
hand               3
dob            44242
ioc             1091
height         68694
wikidata_id    66329
dtype: int64

No hi ha cap na a player_id però tenim jugadors sense noms ni cognoms...

In [38]:
players['player_id'].isna().sum()

np.int64(0)

In [39]:
players[['name_first', 'name_last']].isna().all(axis=1).sum()

np.int64(48)

In [40]:
def clean_players_df(players):

    # Faig drop na de player_id però no n'hi ha cap. 
    player_id = players['player_id']\
        .dropna()\
        .astype(int)\
        .rename('player_id')

    name_first = players['name_first']\
        .fillna('Desconegut')\
        .replace({'X': 'Desconegut'})\
        .astype(str)\
        .rename('First Name')

    name_last = players['name_last']\
        .fillna('Desconegudez')\
        .replace({'X': 'Desconegudez'})\
        .astype(str)\
        .rename('Last Name')

    hand = players['hand']\
        .fillna('U')\
        .astype(str)\
        .rename('Hand')

    country = players['ioc']\
        .fillna('UNK')\
        .astype(str)\
        .rename('Country')

    height = players['height']\
        .fillna(0)\
        .astype(int)\
        .rename('Height')
    
    wikidata_id = players['wikidata_id']\
        .fillna('NOID')\
        .astype(str)\
        .rename('wikidata_id')

    clean_players = pd.concat(
        [wikidata_id,
        name_first,
        name_last,
        hand,
        country,
        height],
        axis=1
    ).set_index(player_id)

    return clean_players

In [41]:
clean_players = clean_players_df(players)
clean_wta_players = clean_players_df(wta_players)

In [42]:
clean_players.isna().sum()

wikidata_id    0
First Name     0
Last Name      0
Hand           0
Country        0
Height         0
dtype: int64

In [43]:
clean_wta_players.isna().sum()

wikidata_id    0
First Name     0
Last Name      0
Hand           0
Country        0
Height         0
dtype: int64

In [44]:
clean_players.to_csv('../web_data/clean_atp_players.csv')
clean_wta_players.to_csv('../web_data/clean_wta_players.csv')

In [45]:
clean_wta_players

          wikidata_id  First Name     Last Name Hand Country  Height
player_id
113190           NOID       Bobby         Riggs    U     USA       0
200000           NOID  Desconegut  Desconegudez    U     UNK       0
200001        Q134720     Martina        Hingis    R     SUI     170
200002        Q239686     Mirjana         Lucic    R     CRO     181
200003         Q11682     Justine         Henin    R     BEL     167
...               ...         ...           ...  ...     ...     ...
270041           NOID       Emily          Dunn    U     NZL       0
270042           NOID      Serena      Rodricks    U     IND       0
270043           NOID        Isha        Mohite    U     IND       0
270044           NOID         Una         Misic    U     NZL       0
270045           NOID       Dorea        Morina    U     NZL       0

[70036 rows x 6 columns]

In [51]:
clean_players[clean_players['wikidata_id']!='NOID'].value_counts().sum()

np.int64(4894)

In [48]:
clean_data[clean_data['tourney_date'].astype(str).str[:4] != clean_data['tourney_id'].str[:4]]

,match_id,tour_year,tourney_id,tourney_name,surface,tourney_level,tourney_date,match_num,score,best_of,round,num_sets,winner_id,winner_name,loser_id,loser_name
6850,1972-301289,1972,1972-301,Auckland,Grass,A,1971-12-06,289,6-3 6-2 6-2,5,R16,3,100135,Onny Parun,100090,Dick Crealy
6851,1972-301290,1972,1972-301,Auckland,Grass,A,1971-12-06,290,6-3 7-6 7-6,5,R16,3,100047,Bob Carmichael,100093,William Brown
6852,1972-301291,1972,1972-301,Auckland,Grass,A,1971-12-06,291,7-5 2-6 6-3 6-3,5,R16,4,100096,Peter Burwash,100082,Roger Dowdeswell
6853,1972-301292,1972,1972-301,Auckland,Grass,A,1971-12-06,292,6-4 4-6 6-3 6-4,5,R16,4,100079,Bill Bowrey,100203,Phil Dent
6854,1972-301293,1972,1972-301,Auckland,Grass,A,1971-12-06,293,6-4 6-3 6-2,5,R16,3,100244,John Alexander,100223,Jeff Simpson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171554,2019-M020272,2019,2019-M020,Brisbane,Hard,A,2018-12-31,272,7-6(6) 6-7(6) 6-0,3,R32,3,105357,John Millman,105815,Tennys Sandgren
171555,2019-M020273,2019,2019-M020,Brisbane,Hard,A,2018-12-31,273,6-3 6-4,3,R32,2,105777,Grigor Dimitrov,106415,Yoshihito Nishioka
171556,2019-M020275,2019,2019-M020,Brisbane,Hard,A,2018-12-31,275,6-4 7-6(6),3,R32,2,106034,Yasutaka Uchiyama,200005,Ugo Humbert
171557,2019-0451297,2019,2019-0451,Doha,Hard,A,2018-12-31,297,4-6 6-3 6-4,3,QF,3,104925,Novak Djokovic,105932,Nikoloz Basilashvili
171558,2019-M020276,2019,2019-M020,Brisbane,Hard,A,2018-12-31,276,4-6 6-3 6-4,3,R32,3,104871,Jeremy Chardy,105526,Jan Lennard Struff