# Preprocess all the matches

#### Libraries

In [12]:
import pandas as pd
import os
from pathlib import Path
from tqdm import tqdm
from datetime import datetime

#### Functions

In [13]:
def load_all_df(folder_path) -> pd.DataFrame:
    folder = Path(folder_path)

    df = pd.DataFrame()
    
    for subdir, dirs, files in os.walk(folder):
        for file in tqdm(sorted(files), total=len(files)-1):
            if file.endswith('.csv'):
                file_path = os.path.join(subdir, file)
                data = pd.read_csv(file_path)
                df = pd.concat([df, data], axis = 0)

    return df

In [14]:
def clean_df(data):

    tourney_id = data['tourney_id']\
        .astype(str)\
        .rename('tourney_id')
    
    match_year = data['tourney_id']\
        .astype(str)\
        .str[:4]\
        .rename('match_year')
    
    tourney_name = data['tourney_name']\
        .astype(str)\
        .rename('tourney_name')
    
    surface = data['surface']\
        .astype(str)\
        .fillna('Unknown')\
        .replace('nan', 'Unknown')\
        .rename('surface')
    
    # draw_size = data['draw_size']\
    #     .fillna(0)\
    #     .replace('nan', 0)\
    #     .astype(int)\
    #     .rename('draw_size')
    
    tourney_level = data["tourney_level"]\
        .astype(str)\
        .rename('tourney_level')
    
    tourney_date = pd.to_datetime(data['tourney_date'], format='%Y%m%d').rename('tourney_date')

    # tourney_date = data["tourney_date"]\
    #     .astype(int)\
    #     .rename('tourney_date')
    
    match_num = data["match_num"]\
        .astype(int)\
        .rename('match_num')
    
    match_id = (data['tourney_id'].astype(str) + data['match_num'].astype(str))\
        .astype(str)\
        .rename('match_id')

    score = data["score"]\
        .astype(str)\
        .replace('nan', 'Unknown')\
        .rename('score')
    
    best_of = data["best_of"]\
        .astype(int)\
        .rename('best_of')
    
    round = data["round"]\
        .astype(str)\
        .rename('round')

    num_sets = data['score']\
        .apply(lambda x: len(x.split()) if isinstance(x, str) else 0)\
        .rename('num_sets')
    

    winner_id = data['winner_id']\
        .astype(int)\
        .rename('winner_id')
    
    winner_name = data['winner_name']\
        .astype(str)\
        .rename('winner_name')
    
    # winner_rank_points = data['winner_rank_points']\
    #     .astype(int)\
    #     .rename('winner_rank_points')
    
    loser_id = data['loser_id']\
        .astype(int)\
        .rename('loser_id')
    
    loser_name = data['loser_name']\
        .astype(str)\
        .rename('loser_name')
    
    # loser_rank_points = data['loser_rank_points']\
    #     .astype(int)\
    #     .rename('loser_rank_points')
    
    cleaned_df = pd.concat(
        [   
            match_id,
            match_year,
            tourney_id, 
            tourney_name, 
            surface, 
            # draw_size, 
            tourney_level, 
            tourney_date, 
            match_num, 
            score, 
            best_of, 
            round, 
            num_sets,
            winner_id, 
            winner_name, 
            # winner_rank_points, 
            loser_id, 
            loser_name],
            # loser_rank_points], 
         axis=1)
    
    assert cleaned_df.isna().sum().sum() == 0,\
        f'There are {cleaned_df.isna().sum()} nan values'
    
    return cleaned_df

#### Treating data

In [15]:
dataframe = load_all_df('../data/atp_matches')
wta_dataframe = load_all_df('../data/wta_matches')

  7%|▋         | 4/54 [00:00<00:02, 16.92it/s]

55it [00:04, 11.29it/s]
57it [00:04, 11.54it/s]

In [16]:
dataframe[(dataframe['tourney_date']>20131229) & (dataframe['tourney_date']<20141121)]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
27,2014-891,Chennai,Hard,28,A,20131230,1,103794,NaN,NaN,...,28.0,15.0,9.0,7.0,2.0,5.0,79.0,637.0,86.0,612.0
28,2014-891,Chennai,Hard,28,A,20131230,2,105379,NaN,NaN,...,60.0,48.0,20.0,16.0,5.0,6.0,95.0,573.0,244.0,191.0
29,2014-891,Chennai,Hard,28,A,20131230,3,104628,NaN,Q,...,53.0,41.0,13.0,14.0,4.0,7.0,270.0,170.0,58.0,810.0
30,2014-891,Chennai,Hard,28,A,20131230,4,106026,NaN,WC,...,35.0,25.0,10.0,10.0,0.0,4.0,195.0,258.0,64.0,739.0
31,2014-891,Chennai,Hard,28,A,20131230,5,104229,NaN,NaN,...,44.0,23.0,4.0,9.0,4.0,10.0,65.0,730.0,89.0,600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,2014-605,Tour Finals,Hard,8,F,20141109,511,103819,2.0,NaN,...,28.0,22.0,15.0,9.0,4.0,6.0,2.0,8700.0,8.0,4440.0
2894,2014-605,Tour Finals,Hard,8,F,20141109,512,104918,5.0,NaN,...,33.0,23.0,14.0,10.0,2.0,5.0,6.0,4475.0,8.0,4440.0
2895,2014-605,Tour Finals,Hard,8,F,20141109,513,103819,2.0,NaN,...,47.0,38.0,36.0,17.0,6.0,9.0,2.0,8700.0,4.0,4895.0
2896,2014-605,Tour Finals,Hard,8,F,20141109,514,104925,1.0,NaN,...,38.0,29.0,5.0,11.0,3.0,9.0,1.0,10010.0,5.0,4625.0
2897,2014-605,Tour Finals,Hard,8,F,20141109,515,104925,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10010.0,2.0,8700.0

In [17]:
clean_data = clean_df(dataframe)
clean_wta_data = clean_df(wta_dataframe)

In [18]:
clean_data.columns

Index(['match_id', 'match_year', 'tourney_id', 'tourney_name', 'surface',
       'tourney_level', 'tourney_date', 'match_num', 'score', 'best_of',
       'round', 'num_sets', 'winner_id', 'winner_name', 'loser_id',
       'loser_name'],
      dtype='object')

In [19]:
clean_wta_data.columns

Index(['match_id', 'match_year', 'tourney_id', 'tourney_name', 'surface',
       'tourney_level', 'tourney_date', 'match_num', 'score', 'best_of',
       'round', 'num_sets', 'winner_id', 'winner_name', 'loser_id',
       'loser_name'],
      dtype='object')

In [20]:
clean_data.isna().sum()

match_id         0
match_year       0
tourney_id       0
tourney_name     0
surface          0
tourney_level    0
tourney_date     0
match_num        0
score            0
best_of          0
round            0
num_sets         0
winner_id        0
winner_name      0
loser_id         0
loser_name       0
dtype: int64

In [21]:
clean_wta_data.isna().sum()

match_id         0
match_year       0
tourney_id       0
tourney_name     0
surface          0
tourney_level    0
tourney_date     0
match_num        0
score            0
best_of          0
round            0
num_sets         0
winner_id        0
winner_name      0
loser_id         0
loser_name       0
dtype: int64

#### Save data to csv

In [22]:
clean_data.to_csv('../web_data/clean_atp_matches.csv')
clean_wta_data.to_csv('../web_data/clean_wta_matches.csv')

# Players

In [23]:
players = pd.read_csv('../data/atp_players.csv')
wta_players = pd.read_csv('../data/wta_players.csv')

/var/folders/s3/s4gmfm1j23xg8_5fnbsqlflm0000gp/T/ipykernel_18370/1323896356.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('../data/atp_players.csv')
/var/folders/s3/s4gmfm1j23xg8_5fnbsqlflm0000gp/T/ipykernel_18370/1323896356.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  wta_players = pd.read_csv('../data/wta_players.csv')

In [24]:
wta_players.isna().sum()

player_id          0
name_first      4208
name_last          0
hand               3
dob            44242
ioc             1091
height         68694
wikidata_id    66329
dtype: int64

No hi ha cap na a player_id però tenim jugadors sense noms ni cognoms...

In [25]:
players['player_id'].isna().sum()

np.int64(0)

In [26]:
players[['name_first', 'name_last']].isna().all(axis=1).sum()

np.int64(48)

In [27]:
def clean_players_df(players):

    # Faig drop na de player_id però no n'hi ha cap. 
    player_id = players['player_id']\
        .dropna()\
        .astype(int)\
        .rename('player_id')

    name_first = players['name_first']\
        .fillna('Desconegut')\
        .replace({'X': 'Desconegut'})\
        .astype(str)\
        .rename('First Name')

    name_last = players['name_last']\
        .fillna('Desconegudez')\
        .replace({'X': 'Desconegut'})\
        .astype(str)\
        .rename('Last Name')

    hand = players['hand']\
        .fillna('U')\
        .astype(str)\
        .rename('Hand')

    country = players['ioc']\
        .fillna('UNK')\
        .astype(str)\
        .rename('Country')

    height = players['height']\
        .fillna(0)\
        .astype(int)\
        .rename('Height')

    clean_players = pd.concat(
        [
        name_first,
        name_last,
        hand,
        country,
        height],
        axis=1
    ).set_index(player_id)

    return clean_players

In [28]:
clean_players = clean_players_df(players)
clean_wta_players = clean_players_df(wta_players)

In [29]:
clean_players.isna().sum()

First Name    0
Last Name     0
Hand          0
Country       0
Height        0
dtype: int64

In [30]:
clean_wta_players.isna().sum()

First Name    0
Last Name     0
Hand          0
Country       0
Height        0
dtype: int64

In [31]:
clean_players.to_csv('../web_data/clean_atp_players.csv')
clean_wta_players.to_csv('../web_data/clean_wta_players.csv')

In [32]:
clean_players[clean_players['First Name']== 'X']

Empty DataFrame
Columns: [First Name, Last Name, Hand, Country, Height]
Index: []

In [33]:
clean_wta_players

           First Name   Last Name Hand Country  Height
player_id
113190          Bobby       Riggs    U     USA       0
200000     Desconegut  Desconegut    U     UNK       0
200001        Martina      Hingis    R     SUI     170
200002        Mirjana       Lucic    R     CRO     181
200003        Justine       Henin    R     BEL     167
...               ...         ...  ...     ...     ...
270041          Emily        Dunn    U     NZL       0
270042         Serena    Rodricks    U     IND       0
270043           Isha      Mohite    U     IND       0
270044            Una       Misic    U     NZL       0
270045          Dorea      Morina    U     NZL       0

[70036 rows x 5 columns]

In [34]:
clean_players.to_csv('../web_data/clean_atp_players.csv')